### Stock
POST http://localhost:3000/api/batches
Content-Type: application/json

{
    "name": "Lote 1",
    "costPerBird": 100,
    "initialQuantity": 100
}

###

POST http://localhost:3000/api/batches
Content-Type: application/json

{
    "name": "Lote 2",
    "costPerBird": 100,
    "initialQuantity": 100,
    "status": "CLOSED"
}

###
GET http://localhost:3000/api/batches

### Loss
POST http://localhost:3000/api/losses
Content-Type: application/json

{
    "batchId": "6f9937ca-35ce-4161-bbcb-1c1e94981636",
    "quantity": 10,
    "reason": "Morte"
}

###
GET http://localhost:3000/api/losses

### Clients

POST http://localhost:3000/api/clients/create
Content-Type: application/json

{
    "name": "Victor",
    "phone": "84999999999"
}

###
GET http://localhost:3000/api/clients/list

### Sale

POST http://localhost:3000/api/sales/register
Content-Type: application/json

{
    "batchId": "6f9937ca-35ce-4161-bbcb-1c1e94981636",
    "customerId": "dec0059d-31aa-49a0-83cb-69fce2ab1205",
    "quantity": 10,
    "unitPrice": 100
}

### 
GET http://localhost:3000/api/sales/6f9937ca-35ce-4161-bbcb-1c1e94981636

### Sales by client
GET http://localhost:3000/api/sales/client/dec0059d-31aa-49a0-83cb-69fce2ab1205
